# TODO improve and update linters as the app is built
run:
  timeout: 5m
  skip-dirs:
    - .github

linters:
  enable:
    - asciicheck
    - revive
    - gosimple
    - govet
    - ineffassign
    - errname
    - errorlint
    - stylecheck
    - gosec
    - prealloc
    - unparam
    - unused
    - whitespace
    - unconvert
    - unused
  disable:
    - errcheck

linters-settings:
  gosec:
    excludes:
      - 'G401' # ignore md5 rules as its used only for hashing trivial value
      - 'G501' # ignore md5 rules as its used only for hashing trivial value
      - 'G404' # Use of weak random number generator
