= Fruits Application (Gloo Enterprise)

A Fruits API demo to demonstrate Gloo Enterprise features with https://istio.io[Istio].As part of the demo, we will deploy the app that will use Istio Proxy from version 1.10.2. The application also uses https://docs.solo.io/gloo-edge/latest[Gloo Edge] as the application gateway to route the traffic between multiple revisions of istio.

== Pre-requisites

* https://docs.docker.com/desktop/[Docker Desktop]
* https://pypa.github.io/pipx[pipx]
* https://kubernetes.io/docs/tasks/tools[kubectl]
* https://httpie.io[httpie]
* Kubernetes Cluster e.g https://kind.sigs.k8s.io[KinD]
* https://docs.solo.io/gloo-edge/latest/getting_started/[Gloo Edge]

== Download Sources

This application has two microservices

1. https://github.com/kameshsampath/go-fruits-api[Fruits API] -  that provides the REST API for managing the Fruits

2. https://github.com/kameshsampath/fruits-app-ui[Fruits App UI]- the front end to the application

[source,shell]
----
git clone https://github.com/kameshsampath/go-fruits-api -b all-in-one go-fruits-api && cd $_
----

We will refer to the cloned folder as `$PROJECT_HOME`:

[source,shell]
----
export PROJECT_HOME="$(pwd)"
----

== Setup Project

Install `pipx` as described in https://pypa.github.io/pipx/installation/

[source,shell]
----
cd $PROJECT_HOME
pipx install ansible
----

== Install Ansible Collection

[source,shell]
----
ansible-galaxy collection install -r requirements.yml
----

== Setup Kubernetes Cluster and Install Istio and Gloo Edge

[IMPORTANT]
=====
Please ensure that you have the Gloo Enterprise License Key and set that as your environment variable `$GLOO_LICENSE_KEY`.
=====

The following commands set up a KinD cluster with Istio and Gloo Edge enterprise,

[source,shell]
----
ansible-playbook cluster-setup-ee.yaml
----

== Deploy Database

[source,shell]
----
k apply -k k8s/db
----
Wait for pods to be in running state:

[source,shell]
----
kubectl rollout status -n db deploy/postgresql --timeout=60s
----

== Deploy application

[source,shell]
----
kustomize build k8s/app | ko resolve -f - | k apply -f -
----

Wait for pods to be in running state:

[source,shell]
----
kubectl rollout status -n fruits-app deploy/fruits-app-api --timeout=60s
----
